name: CI Pipeline with Reusable Workflow
# To get a trigger on every push in this repo in the main branch
on:
  push:
    branches:
      - demo
  pull_request:
    branches:
      - main
permissions:
  actions: read
  security-events: write
  packages: write
  contents: read
jobs:
  selenium-tests:
    uses: kulbhushanmayer/reusable-workflows/.github/workflows/run-selenium-tests.yml@demo
    with:
      ENVIRONMENT: STAGING
