name: CI Pipeline with Reusable Workflow
# To get a trigger on every push in this repo in the main branch
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - HELMCHART-VERSION
permissions:
  actions: read
  security-events: write
  packages: write
  contents: write

env:
  OCI_REGISTRY: ghcr.io
  OCI_REPOSITORY: ${{ github.repository_owner }}/helm-charts
jobs:
  ci-pipeline-job:
    uses: kulbhushanmayer/reusable-workflows/.github/workflows/ci-pipeline.yml@main
    with:
      run_codeql: true
      run_sonarqube: true
      run_build: true
      run_ghcr_publish: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy-with-kubectl:
    needs: ci-pipeline-job
    uses: kulbhushanmayer/reusable-workflows/.github/workflows/deploy-with-kubectl.yml@main
    with:
      ENVIRONMENT: STAGING
      IMAGE_NAME: ghcr.io/kulbhushanmayer/thinknyx_app
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
  selenium-tests:
    needs: deploy-with-kubectl
    uses: kulbhushanmayer/reusable-workflows/.github/workflows/run-selenium-tests.yml@main
    with:
      ENVIRONMENT: STAGING

  publish-helm-chart:
    needs: selenium-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Publish Helm Chart to OCI Registry
        uses: kulbhushanmayer/helm-actions@v1.1
        with: 
          oci_registry: ${{ env.OCI_REGISTRY }}
          oci_repository: ${{ env.OCI_REPOSITORY }}
          auth_token: ${{ secrets.GITHUB_TOKEN }}
        
